export const REQUESTED_TABLEDATA = 'REQUESTED_TABLEDATA'
export const REQUESTED_TABLEDATA_SUCCEEDED = 'REQUESTED_TABLEDATA_SUCCEEDED'
export const REQUESTED_TABLEDATA_FAILED = 'REQUESTED_TABLEDATA_FAILED'




